//! Handing one built request to the daemon, and learning its identity.
//!
//! Submission is separated from observation because a caller may submit and
//! leave. What comes back is an identifier, and the identifier is what makes
//! coming back possible - so everything here exists to make sure the identifier
//! names the same work the second time somebody asks.
//!
//! # Where an identifier comes from decides what a retry means
//!
//! A command that repeats harmlessly gets an identifier generated for it,
//! exactly once, and a reconnect reuses that same value rather than making
//! another. A command that does not gets one from the caller, and refusing to
//! proceed without it is the only way a rerun after a lost response can address
//! the operation that already exists instead of starting a second one.
//!
//! # Nothing is sent until the contracts agree
//!
//! The binding is checked against the installed registry before the daemon is
//! reached: the wire name, the semantic version, the limits digest, and both
//! role-schema digests. A request built against a contract this build does not
//! have is a request the far side would refuse after this process had already
//! spent a round trip and, worse, might have created work.

use slingshot_domain::command::catalog::{Command, CommandCatalog};
use slingshot_domain::selected_command_contract_identity::SelectedCommandContractIdentity;

use crate::daemon_process::{DaemonExpectation, HandshakeRefusal, require_compatible};
use crate::invocation::Invocation;

/// Why one submission cannot be prepared or sent.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum SubmissionRefusal {
    /// The command is not one the installed registry publishes.
    #[error("{named} is not a command this build has installed")]
    NotInstalled {
        /// What was asked for.
        named: String,
    },
    /// The installed identity is not the one the registry describes.
    #[error("this build's {named} does not match the registry it was built from")]
    BindingDrifted {
        /// Which part differs.
        named: &'static str,
    },
    /// A command that changes something was given no caller key.
    #[error("{named} needs the caller key that makes a repeat the same request")]
    OperationKeyRequired {
        /// Which command.
        named: String,
    },
    /// A command that repeats harmlessly was given one anyway.
    #[error("{named} repeats harmlessly, so an operation key would name work nobody tracks")]
    OperationKeyNotTaken {
        /// Which command.
        named: String,
    },
    /// The daemon is not one this client may send work to.
    #[error(transparent)]
    Handshake(#[from] HandshakeRefusal),
}

/// Where one operation identifier came from.
///
/// Kept apart because the two mean different things to a retry. A generated one
/// is stable within this invocation and is regenerated by the next; a supplied
/// one addresses the same operation across processes, which is what makes a
/// rerun after a lost response safe.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OperationKeySource {
    /// The caller supplied it, so a rerun addresses the same operation.
    CallerSupplied(String),
    /// This process generated it, once, for a command that repeats harmlessly.
    GeneratedOnce(String),
}

impl OperationKeySource {
    /// Returns the identifier itself.
    #[must_use]
    pub fn identifier(&self) -> &str {
        match self {
            Self::CallerSupplied(value) | Self::GeneratedOnce(value) => value,
        }
    }

    /// Returns whether a rerun in another process addresses the same operation.
    #[must_use]
    pub fn survives_a_rerun(&self) -> bool {
        matches!(self, Self::CallerSupplied(_))
    }
}

/// One prepared submission, with everything the daemon is told.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubmissionRequest {
    /// Which partition it acts in.
    pub author_target_identity_digest: String,
    /// What to run.
    pub command: Command,
    /// Which runtime contract this client was built against.
    pub daemon_runtime_contract_digest: String,
    /// Where the identifier came from.
    pub key_source: OperationKeySource,
    /// Which environment revision it acts under.
    pub selected_environment_revision: String,
}

/// Requires the installed binding for `wire_name` to be the registry's.
///
/// # Errors
///
/// Returns [`SubmissionRefusal::NotInstalled`] or
/// [`SubmissionRefusal::BindingDrifted`] naming the part that differs.
pub fn require_installed_binding(
    wire_name: &str,
) -> Result<SelectedCommandContractIdentity, SubmissionRefusal> {
    let catalog = CommandCatalog::published();
    let descriptor = catalog
        .find(wire_name)
        .ok_or_else(|| SubmissionRefusal::NotInstalled { named: wire_name.to_owned() })?;
    let identity = SelectedCommandContractIdentity::installed(wire_name)
        .map_err(|_| SubmissionRefusal::NotInstalled { named: wire_name.to_owned() })?;
    let drifted = |named: &'static str| SubmissionRefusal::BindingDrifted { named };
    if identity.command_wire_name != descriptor.wire_name {
        return Err(drifted("wire name"));
    }
    if identity.command_semantic_contract_version != descriptor.command_semantic_contract_version {
        return Err(drifted("semantic version"));
    }
    if identity.command_contract_limits_digest != descriptor.command_contract_limits_sha256 {
        return Err(drifted("limits digest"));
    }
    if identity.argument_schema_digest != descriptor.arguments_schema_sha256 {
        return Err(drifted("argument schema digest"));
    }
    if identity.result_schema_digest != descriptor.result_schema_sha256 {
        return Err(drifted("result schema digest"));
    }
    Ok(identity)
}

/// Returns where the identifier for `wire_name` comes from.
///
/// `generate` is called exactly once, and only for a command that repeats
/// harmlessly. A command that changes something is refused without a supplied
/// key rather than given a generated one, because a generated key would make
/// every rerun a new operation.
///
/// # Errors
///
/// Returns [`SubmissionRefusal::OperationKeyRequired`] or
/// [`SubmissionRefusal::OperationKeyNotTaken`].
pub fn key_source(
    wire_name: &str,
    supplied: Option<&str>,
    generate: impl FnOnce() -> String,
) -> Result<OperationKeySource, SubmissionRefusal> {
    let catalog = CommandCatalog::published();
    let descriptor = catalog
        .find(wire_name)
        .ok_or_else(|| SubmissionRefusal::NotInstalled { named: wire_name.to_owned() })?;
    match (descriptor.intrinsic_idempotency.requires_operation_key(), supplied) {
        (true, Some(value)) => Ok(OperationKeySource::CallerSupplied(value.to_owned())),
        (true, None) => {
            Err(SubmissionRefusal::OperationKeyRequired { named: wire_name.to_owned() })
        }
        (false, None) => Ok(OperationKeySource::GeneratedOnce(generate())),
        (false, Some(_)) => {
            Err(SubmissionRefusal::OperationKeyNotTaken { named: wire_name.to_owned() })
        }
    }
}

/// Returns the submission one invocation and one command produce.
///
/// The daemon's handshake is checked before anything is prepared, so a client
/// that may not send work to this daemon never builds a request for it.
///
/// # Errors
///
/// Returns [`SubmissionRefusal`] naming the first thing that is wrong.
pub fn prepare(
    invocation: &Invocation,
    command: Command,
    expectation: &DaemonExpectation,
    handshake: (&str, &str, &str),
    generate: impl FnOnce() -> String,
) -> Result<SubmissionRequest, SubmissionRefusal> {
    let (runtime_digest, target_digest, revision) = handshake;
    require_compatible(expectation, runtime_digest, target_digest, revision)?;
    require_installed_binding(&invocation.verb)?;
    Ok(SubmissionRequest {
        author_target_identity_digest: expectation.author_target_identity_digest.clone(),
        command,
        daemon_runtime_contract_digest: expectation.runtime_contract_digest.clone(),
        key_source: key_source(&invocation.verb, invocation.operation_key.as_deref(), generate)?,
        selected_environment_revision: expectation.selected_environment_revision.clone(),
    })
}

/// What the daemon said about one submission.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Admission {
    /// It is new work, admitted at this revision.
    Accepted {
        /// The revision it was admitted at.
        revision: u64,
    },
    /// It is work this daemon already holds, unchanged.
    Replayed {
        /// The revision it stands at.
        revision: u64,
    },
}

impl Admission {
    /// Returns the revision the operation stands at.
    #[must_use]
    pub fn revision(self) -> u64 {
        match self {
            Self::Accepted { revision } | Self::Replayed { revision } => revision,
        }
    }

    /// Returns whether this admission created work.
    ///
    /// A replay did not. That distinction is the whole reason a caller-supplied
    /// key exists: without it a rerun could not tell one from the other, and
    /// would have to assume the worse of the two.
    #[must_use]
    pub fn created_work(self) -> bool {
        matches!(self, Self::Accepted { .. })
    }
}

/// What a submission does after the daemon admits it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AfterAdmission {
    /// Report the identifier and return.
    Detach,
    /// Watch the operation until it ends.
    Observe,
}

/// Returns what happens after admission, from what the caller asked for.
///
/// One decision for every command, made from the invocation rather than from
/// what the command is. A branch per command would eventually detach from one
/// and not another for no reason a caller could predict.
#[must_use]
pub fn after_admission(invocation: &Invocation) -> AfterAdmission {
    if invocation.detached { AfterAdmission::Detach } else { AfterAdmission::Observe }
}
